# Generated by Django 2.2.2 on 2019-06-05 16:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goods', '0001_initial'),
        ('trade', '0002_auto_20190605_1512'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShoppingCars',
            new_name='ShoppingCart',
        ),
    ]
