# Generated by Django 2.2.2 on 2019-06-10 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0002_auto_20190605_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userleavingmessage',
            name='file',
            field=models.FileField(default='', help_text='上传的文件', upload_to='message/images/', verbose_name='上传的文件'),
        ),
    ]
